apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
    test: {{ .Values.nestedField.nestedField2.secondInnerField2 }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image -}}:{{ .Values.version }}
        name: {{ .Values.name }}
        env:
        {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: {{ $value }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: http
